### PR TITLE
Libpitt/189 multi rev

### PR DESCRIPTION
**Pull request by libpitt**
Change log:
1. Allow multiple revisions to be created: #190 
-  Added `previous_revision_uuids`, `next_revision_uuids` `list` type properties to provenance_schema.yaml
-  Added `link_to_previous_revisions` and modified `_create_relationship_tx` to accommodate lists via the `IN` operator.
2. Added `/entities/<id>/multi-revisions` endpoint #191 
3. Modified `/previous_revisions/<id>` and `/next_revisions/<id>` to return in multi format ? @yuanzhou or do we need to create new endpoints

On [line there is a TODO](https://github.com/sennetconsortium/entity-api/compare/dev-integrate...libpitt/189-multi-rev?expand=1#diff-04791d82dd15fdd480f084d7ef65a10789fa5012cb7935f76080763444d48a00R2591). I am unsure what the original intent of this code is supposed to do.

Screen Shot 2023-10-04 at 11 48 19 AM
Screen Shot 2023-10-04 at 12 50 27 PM

Please help review, test the changes and advise... 

Thanks.

cc @shirey

### CODE REVIEW

**Comment by libpitt** [comment]
Screen Shot 2023-10-04 at 2 51 56 PM

`on_read` triggers for `previous_revision_uuids` and `next_revision_uuids` filled.

**Comment by libpitt** [comment]
@maxsibilla @yuanzhou 

[For this line](https://github.com/sennetconsortium/entity-api/compare/dev-integrate...libpitt/189-multi-rev?expand=1#diff-7adde3e41007a196a3e3888fe5e8d6dbb25468b9a13eba2204b90abbb14db3e1R722) ...
Thinking maybe don't need this method, but can just extract the `uuid` property via the `app_neo4j_queries.get_sorted_multi_revisions` cypher query alone if preferred. To me preferred via cypher; just trying to copy the format of the original `get_revisions_list` method, where it isn't extracted from the `app_neo4j_queries.get_sorted_revisions` cypher query.

On the other hand, I am seeing within various methods in `schema_neo4j_queries.py` usage of `property_key` ...

**Comment by maxsibilla** [comment]
@libpitt hitting localhost:5002/datasets/d33808e0e05302735f9687df4aa1e3b9/multi-revisions returns this:

```
[
    {
        "revision_number": 2,
        "uuids": [
            "7a9e677def149ac41d1ab9f45153b454"
        ]
    },
    {
        "revision_number": 1,
        "uuids": [
            "d33808e0e05302735f9687df4aa1e3b9"
        ]
    }
]
```

I am not sure how the dataset with uuid `7a9e677def149ac41d1ab9f45153b454` is related or how its being returned here

**Comment by libpitt** [comment]
> d33808e0e05302735f9687df4aa1e3b9

Yes, that looks correct for the graph:
Screen Shot 2023-10-04 at 3 46 04 PM

**Review by maxsibilla — APPROVED** [review]

**Review by yuanzhou — APPROVED** [review]
@libpitt Great work! Everything looks good to me. And to answer your questions in the comments:

>3. Modified /previous_revisions/<id> and /next_revisions/<id> to return in multi format ? @yuanzhou or do we need to create new endpoints

We don't need new endpoints, we just need a list of all the prev or next revision uuids and don't care about their ordering. The API consumer will need to take advantage of multi-revisions endpoint if they need the grouping and ordering.

>On the other hand, I am seeing within various methods in schema_neo4j_queries.py usage of property_key ...

This `property_key`, in most cases is just `uuid` which serves as a filtering to only return back the uuids list when we don't need the full details. The search-api uses this feature during index/reindex runtime, also a performance consideration when the list is big.

**Pull request merged**
